spring:
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: game-watcher

player-manager:
  host: ${PLAYER_MANAGER_HOST}

discord-reporter:
  host: ${GAME_REPORTER_HOST}

riot:
  api-key: ${RIOT_API_KEY}
